ludus:
  - vm_name: "{{ range_id }}-ar-splunk"
    hostname: "{{ range_id }}-ar-splunk"
    template: ubuntu-22.04-x64-server-template
    vlan: 20
    ip_last_octet: 1
    ram_gb: 16
    cpus: 8
    linux: true
    roles:
      - p4t12ick.ludus_ar_splunk

  - vm_name: "{{ range_id }}-ar-windows"
    hostname: "{{ range_id }}-ar-windows"
    template: win2022-server-x64-template
    vlan: 20
    ip_last_octet: 3
    ram_gb: 4
    cpus: 4
    windows:
      sysprep: false
    roles:
      - p4t12ick.ludus_ar_windows
    role_vars:
      ludus_ar_windows_splunk_ip: "10.2.20.1"

  - vm_name: "{{ range_id }}-ar-linux"
    hostname: "{{ range_id }}-ar-linux"
    template: ubuntu-22.04-x64-server-template
    vlan: 20
    ip_last_octet: 2
    ram_gb: 4
    cpus: 4
    linux: true
    roles:
      - p4t12ick.ludus_ar_linux
    role_vars:
      ludus_ar_linux_splunk_ip: "10.2.20.1"

  - vm_name: "{{ range_id }}-kali"
    hostname: "{{ range_id }}-kali"
    template: kali-x64-desktop-template
    vlan: 99
    ip_last_octet: 1
    ram_gb: 4
    cpus: 4
    linux: true
    testing:
      snapshot: false
      block_internet: false

  - vm_name: "{{ range_id }}-mythic-teamserver"
    hostname: "{{ range_id }}-mythic"
    template: debian-12-x64-server-template
    vlan: 99
    ip_last_octet: 2
    ram_gb: 4
    cpus: 4
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - 0xRedpoll.ludus_mythic_teamserver

network:
  external_default: ACCEPT
  wireguard_vlan_default: ACCEPT
  rules:
    - name: Allow kali to mythic
      vlan_src: 99
      ip_last_octet_src: 1
      vlan_dst: 99
      ip_last_octet_dst: 2
      protocol: all
      ports: all
      action: ACCEPT

    - name: Allow mythic to kali
      vlan_src: 99
      ip_last_octet_src: 2
      vlan_dst: 99
      ip_last_octet_dst: 1
      protocol: all
      ports: all
      action: ACCEPT

    - name: Allow windows to mythic
      vlan_src: 20
      ip_last_octet_src: 3
      vlan_dst: 99
      ip_last_octet_dst: 2
      protocol: all
      ports: all
      action: ACCEPT

    - name: Allow mythic to windows
      vlan_src: 99
      ip_last_octet_src: 2
      vlan_dst: 20
      ip_last_octet_dst: 3
      protocol: all
      ports: all
      action: ACCEPT

    - name: Allow linux to mythic
      vlan_src: 20
      ip_last_octet_src: 2
      vlan_dst: 99
      ip_last_octet_dst: 2
      protocol: all
      ports: all
      action: ACCEPT

    - name: Allow mythic to linux
      vlan_src: 99
      ip_last_octet_src: 2
      vlan_dst: 20
      ip_last_octet_dst: 2
      protocol: all
      ports: all
      action: ACCEPT

    - name: Allow linux and windows to Splunk
      vlan_src: 20
      ip_last_octet_src: 2-3  # Range of .2 and .3
      vlan_dst: 20
      ip_last_octet_dst: 1
      protocol: all
      ports: all
      action: ACCEPT
